stages:
    - lint
    - test
    - version

lint:full:
    image: spam312sn/symfony:php7.2-xdebug
    stage: lint
    before_script: # Override global `before_script`
        - php -v
    script:
        - find './' -type f -name '*.php' -not -path './vendor/*' -not -path './var/*' -print0 | xargs -n 1 -0 php -l
    when: manual
    only:
        - merge_requests

test:all:
    image: spam312sn/symfony:php7.2-xdebug
    stage: test
    script:
        - composer install --dev -q
        - php vendor/bin/phpunit
    when: manual
    only:
        - merge_requests

test:coverage:
    image: spam312sn/symfony:php7.2-xdebug
    stage: test
    artifacts:
        paths:
            - tests/output/
        expire_in: 2 day
    script:
        - composer install --dev -q
        - php vendor/bin/phpunit --coverage-html=tests/output --coverage-text --colors=never
    when: manual
    only:
        - merge_requests

.setup_git: &setup_git
    before_script:
        - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - git remote set-url origin git@gitlab.com:enuage/bundles/version-updater.git
        - git config --global user.email "spam312sn@gmail.com"
        - git config --global user.name "Serghei Niculaev"
        - git checkout --track origin/master
        - git fetch && git pull

version:major:
    <<: *setup_git
    image: spam312sn/symfony:php7.2-xdebug
    stage: version
    script:
        - composer install -q
        - php bin/version-updater --major
    when: manual
    only:
        - master

version:minor:
    <<: *setup_git
    image: spam312sn/symfony:php7.2-xdebug
    stage: version
    script:
        - composer install -q
        - php bin/version-updater --minor
    when: manual
    only:
        - master

version:patch:
    <<: *setup_git
    image: spam312sn/symfony:php7.2-xdebug
    stage: version
    script:
        - composer install -q
        - php bin/version-updater --patch
    when: manual
    only:
        - master
